### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by frontsidejack**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and publish to npm yourself or [setup this action to publish automatically](https://github.com/changesets/action#with-publishing). If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

# Releases
### Minor Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)

### Patch Changes

-   Updated dependencies [edf4591]
    -   @frontside/backstage-plugin-graphql-backend-node@0.1.0

### Minor Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)

### Patch Changes

-   Updated dependencies [edf4591]
    -   @frontside/backstage-plugin-graphql-backend@0.1.0

### Minor Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)

### Patch Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)

### Patch Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)

### Patch Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)

### Patch Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)
-   Updated dependencies [edf4591]
    -   @frontside/backstage-plugin-incremental-ingestion-backend@0.4.8

### Patch Changes

-   c929ea9: Support entity updates by metadata name

### Patch Changes

-   edf4591: Backport graphql plugins from Backstage PRFC [#15519](https://github.com/backstage/backstage/pull/15519)
-   Updated dependencies [edf4591]
-   Updated dependencies [c929ea9]
    -   @frontside/backstage-plugin-graphql-backend-module-catalog@0.1.0
    -   @frontside/backstage-plugin-incremental-ingestion-backend@0.4.8
    -   @frontside/backstage-plugin-humanitec-backend@0.3.10
    -   @frontside/backstage-plugin-graphql-backend@0.1.0
    -   @frontside/scaffolder-yaml-actions@0.2.3

### CODE REVIEW

**Comment by taras** [comment]
@cowboyd @wKich should we change the version numbers of the graphql plugins to something more representative of the amount of work involved here? 0.0.1 makes it look like something that was created yesterday.

**Comment by wKich** [comment]
yeah, we can. I just used the same numbers as backstage uses for new packages

**Comment by frontsidejack** [comment]
The following preview packages were published:
|                                          Name                                         |                           Version                           | Install Command                                                                                                       |
| :-----------------------------------------------------------------------------------: | :---------------------------------------------------------: | --------------------------------------------------------------------------------------------------------------------- |
|               <br><pre><code>@frontside/graphgen-backstage</code></pre>               |  <br><pre><code>0.3.2-changeset-release-main.0</code></pre> | <br><pre><code>yarn add @frontside/graphgen-backstage@changeset-release-main</code></pre>                             |
|       <br><pre><code>@frontside/backstage-plugin-humanitec-backend</code></pre>       |  <br><pre><code>0.2.5-changeset-release-main.8</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-humanitec-backend@changeset-release-main</code></pre>             |
| <br><pre><code>@frontside/backstage-plugin-incremental-ingestion-backend</code></pre> | <br><pre><code>0.1.2-changeset-release-main.11</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-incremental-ingestion-backend@changeset-release-main</code></pre> |
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Comment by taras** [comment]
How about 0.5.0 to start?

**Review by wKich — APPROVED** [review]

**Review by taras — APPROVED** [review]

**Pull request merged**
