### PR TITLE
Update backstage packages

### PR DESCRIPTION
**Pull request by wKich**
## Approach

Update backstage packages to the latest version

### CODE REVIEW

**Review by taras — APPROVED** [review]
👍

**Review by jbolda — CHANGES_REQUESTED** [review]
It looks like the `lerna` functionality is not working if you could fix that. It also looks like it isn't starting up in dev mode either.
Screenshot 2024-03-12 at 12 45 13 PM

It looks like `yarn backstage-cli versions:check` doesn't raise any issues.

**Comment by taras** [comment]
> It also looks like it isn't starting up in dev mode either. Screenshot 2024-03-12 at 12 45 13 PM

This is this problem https://github.com/backstage/backstage/issues/22142#issuecomment-1881770676

**Comment by frontsidejack** [comment]
The following preview packages were published:
|                                          Name                                          |                          Version                         | Install Command                                                                                                     |
| :------------------------------------------------------------------------------------: | :------------------------------------------------------: | ------------------------------------------------------------------------------------------------------------------- |
|            <br><pre><code>@frontside/backstage-ingestion-tests</code></pre>            |  <br><pre><code>0.7.1-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-ingestion-tests@dl-update-backstage</code></pre>                       |
|          <br><pre><code>@frontside/backstage-plugin-batch-loader</code></pre>          |  <br><pre><code>0.4.1-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-batch-loader@dl-update-backstage</code></pre>                   |
|       <br><pre><code>@frontside/backstage-plugin-effection-inspector</code></pre>      | <br><pre><code>0.1.12-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-effection-inspector@dl-update-backstage</code></pre>            |
|   <br><pre><code>@frontside/backstage-plugin-effection-inspector-backend</code></pre>  | <br><pre><code>0.1.12-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-effection-inspector-backend@dl-update-backstage</code></pre>    |
|      <br><pre><code>@frontside/backstage-plugin-graphql-backend-node</code></pre>      |  <br><pre><code>0.1.5-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-graphql-backend-node@dl-update-backstage</code></pre>           |
|        <br><pre><code>@frontside/backstage-plugin-humanitec-common</code></pre>        | <br><pre><code>0.3.13-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-humanitec-common@dl-update-backstage</code></pre>               |
|  <br><pre><code>@frontside/backstage-plugin-incremental-ingestion-backend</code></pre> |  <br><pre><code>0.5.1-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-incremental-ingestion-backend@dl-update-backstage</code></pre>  |
|       <br><pre><code>@frontside/backstage-plugin-scaffolder-workflow</code></pre>      | <br><pre><code>0.10.1-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-scaffolder-workflow@dl-update-backstage</code></pre>            |
|             <br><pre><code>@frontside/scaffolder-yaml-actions</code></pre>             |  <br><pre><code>0.3.1-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/scaffolder-yaml-actions@dl-update-backstage</code></pre>                         |
|         <br><pre><code>@frontside/backstage-plugin-graphql-backend</code></pre>        |  <br><pre><code>0.1.7-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-graphql-backend@dl-update-backstage</code></pre>                |
|            <br><pre><code>@frontside/backstage-plugin-humanitec</code></pre>           | <br><pre><code>0.3.15-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-humanitec@dl-update-backstage</code></pre>                      |
|        <br><pre><code>@frontside/backstage-plugin-humanitec-backend</code></pre>       | <br><pre><code>0.3.17-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-humanitec-backend@dl-update-backstage</code></pre>              |
|  <br><pre><code>@frontside/backstage-plugin-incremental-ingestion-github</code></pre>  | <br><pre><code>0.2.12-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-incremental-ingestion-github@dl-update-backstage</code></pre>   |
| <br><pre><code>@frontside/backstage-plugin-graphql-backend-module-catalog</code></pre> |  <br><pre><code>0.2.6-dl-update-backstage.2</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-graphql-backend-module-catalog@dl-update-backstage</code></pre> |
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Comment by wKich** [comment]
@taras I've just updated `react` to 18.x :) Seems like it works

**Review by jbolda — APPROVED** [review]

**Pull request merged**
