### PR TITLE
union of world

### PR DESCRIPTION
**Pull request by dagda1**
## Motivation
 
We need `__typename` added to each type and `World`.

## Approach

Create a `UnionOfWorld` mapped type that adds takes the property key from the `World` type and uses it for the `__typename`.

### CODE REVIEW

**Comment by frontsidejack** [comment]
The following preview packages were published:
|                               Name                              |                        Version                        | Install Command                                                                            |
| :-------------------------------------------------------------: | :---------------------------------------------------: | ------------------------------------------------------------------------------------------ |
| <br><pre><code>@frontside/backstage-plugin-graphql</code></pre> | <br><pre><code>0.1.1-pc-union-of-world.0</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-graphql@pc-union-of-world</code></pre> |
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Comment by cowboyd** [comment]
@dagda1 Can we not do this automatically in graphgen? Otherwise, every single project that uses graphgen will need to replicate this behavior.

**Comment by dagda1** [comment]
> @dagda1 Can we not do this automatically in graphgen? Otherwise, every single project that uses graphgen will need to replicate this behavior.

If this was for graphgen should we not have used it as the example?

I'm afraid that, again, I'm missing a lot of context of actually what is required here, and I'm trying to piece it together without much to go on.

I honestly don't know what the next line means

> Otherwise, every single project that uses graphgen will need to replicate this behavior.

The mapped type can be used anywhere and will create a union with `__typnename`.

But the original brief was to be able to narrow by typename in the example but actually it is something else that is required.

**Comment by cowboyd** [comment]
> But the original brief was to be able to narrow by typename in the example but actually it is something else that is required.

Apologies if this came off as me not being pleased with the solution. I definitely am. I didn't see the way forward, but after you showed me, I was asking, can we provide this out-of-the-box with graphgen, so that nobody else but us has to write this type.

**Comment by dagda1** [comment]
@cowboyd no need to apologise and actually I apologise for the last response.  I think I know what you mean now, and all I had to was ask for clarity.  

So the first step is to make the mapped type generic

```ts
export type UnionOfNodes<T> = {
  [K in keyof T]: {
    __typename: K,
  } & T[K]
}[keyof T]
```

I think one of the problems is that `Node` already has a `__typename` of `string` and it gets smashed onto a lot of things with `& Node` .

So I think we can apply `UnionOfNodes` to the type that gets passed into `createGraphGen` but the tricky bit is how to return that to the client code and also in hp we the code generator is creating `__typename` fields on the types as it is.

I definitely think it is possible but I think I want to give it a bit of thought.

**Comment by dagda1** [comment]
Here is a [playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDiwYBVnAHICGAtsADxYA0cA0gHxwC8cWcoMwAdgCYDOcA3gCg4cAPqikKDsWAAuOAEsOAM2BQ4AVUEBfOAH5NcedQDcgwaEiwEuTRwUQOAeWV4IXYD3L0mQkQG1qRQ44AGtgRAhlZgBdeT8RMQlcaRJ5DGxcQhJyQJiqOmE4XQAyZjydf3DI6KwYs0EldihlAgBjVAAJAh4cFGzUBPFJThl5AHIAQWmZmfGzEVS5OB4YKCUAczNtc0aOZtaOuG6eNz78GQEitogAG2gJqGAucbgAHzhxgCNbgFdgV4fcYbJ6ceY6cwjOBuDx8XxFE7nAbyRFZGQLY49M5otKY04QJHoiGCZS-DhtGAOEJcCAASRgAAoOO5lhp7I4XDDPKQuTxaABKK4iBTKJksgB0wxSlwYss+J2x-Rk40FCRENw4PDuwHF9w2Yo84pu9yg-IxOyKIoNOqlUhlcqms1mKqFiQ1WtuOr11vFS35RR2OyAA) of how to deal with types that already have a `__typename`

```ts
export type GetTypeName<T, K> = T extends {
  __typename: infer U
} ? U : K;

export type UnionOfNodes<T> = {
  [K in keyof T]: {
    __typename: GetTypeName<T[K], K>
  } & T[K]
}[keyof T];

interface HasTypeName {
  __typename: 'AAAAAAAAA';
  name: string;
}


interface HasNoTypeName {
  color: 'red' | 'blue' | 'green';
}

type Nodes = {
  HasTypeName: HasTypeName;
  HasNoTypeName: HasNoTypeName;
}

function doIt(node: UnionOfNodes<Nodes>) {
  if(node.__typename === 'HasNoTypeName') {
    console.log(node.color);
  }

  if(node.__typename === 'AAAAAAAAA') {
    console.log(node.name)
  }
}
```

**Comment by dagda1** [comment]
@cowboyd if you have any time to pair on this tomorrow then let me know.  This is definitely a good problem.

**Review by cowboyd — APPROVED** [review]

**Comment by cowboyd** [comment]
> @cowboyd if you have any time to pair on this tomorrow then let me know. This is definitely a good problem.

Yeah, I'm going to go ahead and merge this, but let's see if we can't get it into graphgen tomorrow.

**Comment by dagda1** [comment]
> Yeah, I'm going to go ahead and merge this, but let's see if we can't get it into graphgen tomorrow.

I would not merge this, there are gotchas

**Comment by cowboyd** [comment]
Seems like we may not want to go with a fancy solution, and just include `__typename` in the interface.

**Pull request closed without merging**
