### PR TITLE
Upgrade to Backstage 1.11.1

### PR DESCRIPTION
**Pull request by taras**
## Motivation

I want to make sure that we're on the latest and greatest

## Approach

Bump up version using `npx @backstage/cli versions:bump`

### CODE REVIEW

**Comment by taras** [comment]
@dagda1 is it ok to upgrade alpha versions of scaffolder to 1.11?

**Comment by dagda1** [comment]
> @dagda1 is it ok to upgrade alpha versions of scaffolder to 1.11?

I think so, the last time I had anything merged was 2 weeks ago and the last release was the 14th

**Comment by frontsidejack** [comment]
📣 NOTIFICATION
You are receiving this message because we did not publish any packages.
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Comment by taras** [comment]
@dagda1 ok, can you please give me a review when you have a moment.

**Review by dagda1 — APPROVED** [review]

**Pull request merged**
