### PR TITLE
Upgrade To Backstage v1.7

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

This upgrades to Backstage 1.7 for that latest and greatest.

## Approach

Ran the backstage upgrade command and checked the versions that `create-app` uses to confirm.

### CODE REVIEW

**Comment by frontsidejack** [comment]
📣 NOTIFICATION
You are receiving this message because we did not publish any packages.
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Comment by jbolda** [comment]
Note this did include a Jest upgrade to v29. Tests seem to pass but we [get a warning](https://github.com/thefrontside/backstage/actions/runs/3316580373/jobs/5478534947#step:8:14). Not sure if this is an issue.

```
    console.warn
      Warning: [JSS] CSSOM.parse is not a function
```

**Comment by cowboyd** [comment]
It sounds like it can be safely suppressed https://github.com/jsdom/jsdom/issues/2026#issuecomment-339078997

**Comment by jbolda** [comment]
Seems like it was fixed more recently, but we have a pretty old version of `cssom` held back by some backstage deps. It seems ignoring is the best path here.

**Review by cowboyd — APPROVED** [review]

**Pull request merged**
