### PR TITLE
Remove init method from batch-loader plugin

### PR DESCRIPTION
**Pull request by wKich**
## Motivation

According this comment https://github.com/backstage/backstage/issues/12254#issuecomment-1217793906 backstage has `refresh_state` table with `entity_ref` column, which we can use to query multiple entity refs at the same time

## Approach

Remove migrations, `init` method and refactor get entities query to use join between two tables

### CODE REVIEW

**Comment by frontsidejack** [comment]
The following preview packages were published:
|                                 Name                                 |                          Version                         | Install Command                                                                                    |
| :------------------------------------------------------------------: | :------------------------------------------------------: | -------------------------------------------------------------------------------------------------- |
| <br><pre><code>@frontside/backstage-plugin-batch-loader</code></pre> | <br><pre><code>0.1.2-dl-remove-migrations.0</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-batch-loader@dl-remove-migrations</code></pre> |
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Review by taras — COMMENTED** [review]
can you tell if there is any impact on performance?

**Comment by wKich** [comment]
@taras It's in 10-20 ms slower. But it's not big deal in comparison with catalog api
image

**Review by taras — APPROVED** [review]
👍

**Pull request merged**
