### PR TITLE
Update backstage packages and fix broken changes

### PR DESCRIPTION
**Pull request by wKich**
## Motivation

For #9 we want to use `getEntityByRef` for querying entities instead of deprecated `getEntityByName`. But our backstage packages are outdated.

## Approach

- Update backstage packages by using `yarn upgrade-interactive --latest`
- Run migration commands from https://backstage.io/docs/tutorials/package-role-migration#tldr-step-1-4
- Run `yarn-deduplicate`
- Check backstage changelogs to fix broken parts

### CODE REVIEW

**Review by taras — COMMENTED** [review]
How did you perform this upgrade? You should add that into Approach. Did you use `yarn versions:bump`? What do you get when you run `yarn versions:check`?

**Comment by wKich** [comment]
@taras updated "Approach"

**Review by taras — COMMENTED** [review]
Please run `yarn backstage-cli versions:check` and see what that reports. Also, try `yarn backstage-cli versions:bump` to see if you might have missed anything.

**Review by taras — APPROVED** [review]
Feel free to merge when there are no errors in `yarn backstage-cli versions:check`. Please post output to a comment before you do.

**Comment by wKich** [comment]
image

**Pull request merged**
