### PR TITLE
Upgrade to Backstage 1.6

### PR DESCRIPTION
**Pull request by taras**
## Motivation

We want to be using the latest and greatest Backstage hits. It's difficult to do when we're not running the latest version of Backstage. This PR upgrades everything to Backstage 1.6.

## Approach

Ran `yarn backstage-cli versions:bump` and then followed the changes in https://backstage.github.io/upgrade-helper/?from=1.3.1&to=1.6.0

### CODE REVIEW

**Comment by frontsidejack** [comment]
📣 NOTIFICATION
You are receiving this message because we did not publish any packages.
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions Frontside</a><em></p>

**Review by cowboyd — APPROVED** [review]
Looks good... at least nothing that seems off. Personally I'm excited to use with Safari 😁

**Comment by taras** [comment]
It works 
image

**Review by dagda1 — COMMENTED** [review]
🚢

**Pull request merged**
